"use strict";

/**
 * instagramMetaRoutes.js — per-tenant Meta credential entry + generated
 * webhook info endpoints for connecting a tenant's own Instagram Business
 * Account.
 *
 * CORRECTED (2026-07-31): replaces the previous OAuth authorize/callback
 * flow entirely. There is no shared platform Meta App — each clinic (tenant)
 * creates their OWN Meta Developer App at developers.facebook.com (outside
 * our system) and manually enters their App ID, App Secret, a long-lived
 * Access Token (generated by the clinic themselves via their own Meta
 * dashboard's Graph API Explorer or their own server-side token exchange —
 * NOT via a redirect through our backend), and their Instagram Business
 * Account ID directly into our settings UI. This is direct credential
 * entry, not OAuth.
 *
 * Our backend's job is to:
 *   1. Persist those tenant-supplied credentials.
 *   2. Generate and display a UNIQUE per-tenant callback/webhook URL and a
 *      UNIQUE per-tenant webhook verify token, which the clinic then pastes
 *      into THEIR OWN Meta App's webhook configuration on
 *      developers.facebook.com.
 *
 * Router factory mirrors the mount style used by whatsapp-qr/instagram-dm's
 * routers. `authMiddleware` is injected by the caller (backend/index.js).
 */

const express = require("express");
const crypto = require("crypto");
const { InstagramSession } = require("../models");
const metaGraph = require("../services/metaGraphApi");
const log = require("../utils/logger");

const MODULE = "InstagramMeta";

const MAX_SLOTS_PER_TENANT = 1;

const normalizeSlot = (raw) => {
  const n = parseInt(raw, 10);
  if (!Number.isFinite(n) || n < 1) return 1;
  return Math.min(n, MAX_SLOTS_PER_TENANT);
};

/** Build the unique per-tenant webhook URL the clinic pastes into their own
 *  Meta App's webhook config. The URL path itself identifies the tenant
 *  (and slot), since the webhook handshake/receive endpoints resolve which
 *  tenant's row to use from this same path pattern. */
const buildWebhookUrl = (tenantId, slot) => {
  const base = (process.env.BACKEND_URL || `http://localhost:${process.env.PORT || 4000}`).replace(/\/+$/, "");
  return `${base}/api/webhooks/instagram/${tenantId}/${slot}`;
};

// Mask a secret for frontend display (show last 4 chars only) — mirrors
// aiSettingController.js's maskKey() convention used for the OpenAI API key.
const maskSecret = (value) => {
  if (!value) return null;
  if (value.length <= 8) return "••••••••";
  return "••••••••••••" + value.slice(-4);
};

const toStatusPayload = (row) => ({
  success: true,
  status: row?.status || "disconnected",
  ig_username: row?.ig_username || null,
  ig_business_account_id: row?.ig_business_account_id || null,
  facebook_page_id: row?.facebook_page_id || null,
  meta_app_id: row?.meta_app_id || null,
  last_error: row?.last_error || null,
  has_credentials: !!(row?.meta_app_id && row?.access_token),
  meta_app_secret_masked: maskSecret(row?.meta_app_secret),
  access_token_masked: maskSecret(row?.access_token),
});

function createInstagramMetaRouter({ authMiddleware } = {}) {
  const router = express.Router();

  // PUT /api/instagram-meta/:slot/credentials — save/update a tenant's own
  // Meta App credentials + Instagram Business Account ID. Direct credential
  // entry, not an OAuth exchange.
  router.put("/:slot/credentials", authMiddleware, async (req, res) => {
    try {
      const tenantId = req.user?.tenant_id || req.user?.id;
      if (!tenantId) return res.status(400).json({ success: false, message: "No tenant" });
      const slot = normalizeSlot(req.params.slot);

      const { meta_app_id, meta_app_secret, access_token, ig_business_account_id, facebook_page_id, label } = req.body || {};

      const [row] = await InstagramSession.findOrCreate({
        where: { tenant_id: tenantId, slot },
        defaults: { tenant_id: tenantId, slot },
      });

      // meta_app_secret/access_token are optional on UPDATE (blank = "keep the
      // currently saved value", per the frontend's "leave blank to keep"
      // helper text) but required on the FIRST save, since there is nothing
      // stored yet to fall back to. ig_business_account_id is ALWAYS required
      // (manual entry only) — auto-resolving it from the access token via
      // Pages -> linked IG account requires pages_show_list permission that
      // manually-generated tokens (e.g. from Graph API Explorer) typically
      // don't have, so that auto-detect path was removed as unreliable.
      const isFirstSave = !row.meta_app_id && !row.access_token;
      if (!meta_app_id || (isFirstSave && (!meta_app_secret || !access_token)) || (isFirstSave && !ig_business_account_id)) {
        return res.status(400).json({
          success: false,
          message: "meta_app_id, meta_app_secret, access_token, and ig_business_account_id are all required.",
        });
      }

      // Generate the per-tenant webhook verify token once, on first save —
      // never regenerate it on subsequent credential updates, since the
      // clinic has already pasted it into their own Meta App's webhook config
      // and regenerating it would silently break their existing webhook.
      const webhookVerifyToken = row.webhook_verify_token || crypto.randomBytes(24).toString("hex");

      // Blank secret/token on an update means "keep the currently saved
      // value" (per the frontend's helper text) — resolve the EFFECTIVE
      // values used for both the username lookup and the persisted row.
      const effectiveAppSecret = meta_app_secret || row.meta_app_secret;
      const effectiveAccessToken = access_token || row.access_token;
      const igBusinessAccountId = ig_business_account_id || row.ig_business_account_id;

      // Best-effort username lookup for display — do not block saving
      // credentials if this fails (e.g. token permissions, transient error).
      let igUsername = null;
      try {
        igUsername = await metaGraph.getIgBusinessAccountUsername({
          igBusinessAccountId,
          accessToken: effectiveAccessToken,
        });
      } catch (err) {
        log.warn(MODULE, "credentials:usernameLookupFailed", { tenantId, slot, error: err.response?.data || err.message });
      }

      await row.update({
        meta_app_id,
        meta_app_secret: effectiveAppSecret,
        access_token: effectiveAccessToken,
        ig_business_account_id: igBusinessAccountId,
        facebook_page_id: facebook_page_id || row.facebook_page_id || null,
        webhook_verify_token: webhookVerifyToken,
        label: label || row.label || null,
        ig_username: igUsername || row.ig_username || null,
        status: "connected",
        last_error: null,
      });

      return res.json(toStatusPayload(row));
    } catch (err) {
      log.error(MODULE, "credentials", { error: err.message });
      return res.status(500).json({ success: false, message: err.message });
    }
  });

  // GET /api/instagram-meta/:slot/webhook-info — the generated callback URL
  // + verify token the clinic pastes into THEIR OWN Meta App's webhook config.
  router.get("/:slot/webhook-info", authMiddleware, async (req, res) => {
    try {
      const tenantId = req.user?.tenant_id || req.user?.id;
      if (!tenantId) return res.status(400).json({ success: false, message: "No tenant" });
      const slot = normalizeSlot(req.params.slot);

      let row = await InstagramSession.findOne({ where: { tenant_id: tenantId, slot } });
      let webhookVerifyToken = row?.webhook_verify_token;

      // Allow viewing the callback URL + a verify token even before the
      // clinic has saved credentials yet, so they can configure their Meta
      // App's webhook ahead of/alongside entering credentials.
      if (!webhookVerifyToken) {
        webhookVerifyToken = crypto.randomBytes(24).toString("hex");
        const [created] = await InstagramSession.findOrCreate({
          where: { tenant_id: tenantId, slot },
          defaults: { tenant_id: tenantId, slot, webhook_verify_token: webhookVerifyToken },
        });
        if (!created.webhook_verify_token) {
          await created.update({ webhook_verify_token: webhookVerifyToken });
        } else {
          webhookVerifyToken = created.webhook_verify_token;
        }
        row = created;
      }

      return res.json({
        success: true,
        webhook_url: buildWebhookUrl(tenantId, slot),
        verify_token: webhookVerifyToken,
      });
    } catch (err) {
      log.error(MODULE, "webhook-info", { error: err.message });
      return res.status(500).json({ success: false, message: err.message });
    }
  });

  // GET /api/instagram-meta/:slot/status
  router.get("/:slot/status", authMiddleware, async (req, res) => {
    try {
      const tenantId = req.user?.tenant_id || req.user?.id;
      if (!tenantId) return res.status(400).json({ success: false, message: "No tenant" });
      const slot = normalizeSlot(req.params.slot);
      const row = await InstagramSession.findOne({ where: { tenant_id: tenantId, slot } });
      return res.json(toStatusPayload(row));
    } catch (err) {
      return res.status(500).json({ success: false, message: err.message });
    }
  });

  // POST /api/instagram-meta/:slot/disconnect — clears stored credentials.
  router.post("/:slot/disconnect", authMiddleware, async (req, res) => {
    try {
      const tenantId = req.user?.tenant_id || req.user?.id;
      if (!tenantId) return res.status(400).json({ success: false, message: "No tenant" });
      const slot = normalizeSlot(req.params.slot);
      const row = await InstagramSession.findOne({ where: { tenant_id: tenantId, slot } });
      if (row) {
        await row.update({
          status: "disconnected",
          meta_app_id: null,
          meta_app_secret: null,
          access_token: null,
          token_expires_at: null,
          ig_business_account_id: null,
          facebook_page_id: null,
          ig_username: null,
          last_error: null,
          // webhook_verify_token intentionally kept — disconnecting credentials
          // doesn't require the clinic to re-paste a new verify token into
          // their Meta App if they reconnect later.
        });
      }
      return res.json({ success: true });
    } catch (err) {
      return res.status(500).json({ success: false, message: err.message });
    }
  });

  // GET /api/instagram-meta/sessions — list all linked-account slots for the tenant.
  router.get("/sessions", authMiddleware, async (req, res) => {
    try {
      const tenantId = req.user?.tenant_id || req.user?.id;
      if (!tenantId) return res.status(400).json({ success: false, message: "No tenant" });
      const rows = await InstagramSession.findAll({
        where: { tenant_id: tenantId },
        order: [["slot", "ASC"]],
      });
      const sessions = rows.map((r) => ({
        slot: r.slot,
        label: r.label,
        status: r.status,
        ig_username: r.ig_username,
      }));
      return res.json({ success: true, sessions, maxSlots: MAX_SLOTS_PER_TENANT });
    } catch (err) {
      return res.status(500).json({ success: false, message: err.message });
    }
  });

  return router;
}

module.exports = { createInstagramMetaRouter, MAX_SLOTS_PER_TENANT, normalizeSlot, buildWebhookUrl };
