import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Ambulance,
  AppWindow,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Award,
  BadgeDollarSign,
  BadgePlus,
  Banknote,
  BarChart2,
  BarChart3,
  BarChart4,
  Bell,
  BellRing,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Brain,
  BrainCircuit,
  Brush,
  Building,
  Building2,
  Cable,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CircleDollarSign,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  Cog,
  Compass,
  Contact,
  Copy,
  Cpu,
  CreditCard,
  Cross,
  Database,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  File,
  FileCheck,
  FilePlus,
  FileSearch,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Folder,
  FolderOpen,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  Image as ImageIcon,
  Inbox,
  IndianRupee,
  Info,
  Key,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  List,
  Lock,
  Mail,
  MailOpen,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Minus,
  Monitor,
  Music,
  Navigation,
  Notebook,
  Package,
  Package2,
  PackageCheck,
  Palette,
  PanelLeft,
  Phone,
  PhoneCall,
  PieChart,
  PiggyBank,
  Pill,
  Play,
  PlayCircle,
  Plug,
  Plug2,
  PlugZap,
  PlugZap2,
  Plus,
  Printer,
  Puzzle,
  QrCode,
  Receipt,
  RefreshCw,
  RotateCcw,
  Scan,
  ScanFace,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SidebarOpen,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Syringe,
  Table,
  Tablet,
  Tag,
  Tags,
  Thermometer,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Unlock,
  Upload,
  UserCheck,
  UserCircle,
  UserCog,
  UserPlus,
  UserX,
  Users,
  Video,
  Wallet,
  Wand2,
  Warehouse,
  Webhook,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import type { MenuEntry, MenuPermission, PlanFeatureFlags, Role } from "../utils/types";

// ─── Super-admin static menu ─────────────────────────────────────────
export const superAdminMenu: MenuEntry[] = [
  { key: "sa-dashboard",       label: "Dashboard",        icon: <LayoutDashboard size={18} />, path: "/super-admin/dashboard",       roles: ["super_admin"] },
  { key: "sa-tenants",         label: "Clinics",          icon: <Building2 size={18} />,       path: "/super-admin/tenants",         roles: ["super_admin"] },
  { key: "sa-users",           label: "Users",            icon: <Users size={18} />,           path: "/super-admin/users",           roles: ["super_admin"] },
  { key: "sa-leads",           label: "Leads",            icon: <Contact size={18} />,         path: "/super-admin/leads",           roles: ["super_admin"] },
  { key: "sa-conversations",   label: "Conversations",    icon: <MessagesSquare size={18} />,  path: "/super-admin/conversations",   roles: ["super_admin"] },
  { key: "sa-subscriptions",   label: "Subscriptions",    icon: <Package2 size={18} />,        path: "/super-admin/subscriptions",   roles: ["super_admin"] },
  { key: "sa-payments",        label: "Payments",         icon: <CreditCard size={18} />,      path: "/super-admin/payments",        roles: ["super_admin"] },
  { key: "sa-plans",           label: "Plan Master",            icon: <BadgeDollarSign size={18} />, path: "/super-admin/plans",           roles: ["super_admin"] },
  // { key: "sa-ai-settings",     label: "AI Settings",      icon: <Bot size={18} />,             path: "/super-admin/ai-settings",     roles: ["super_admin"] },
  // { key: "sa-logs",            label: "System Logs",      icon: <Gauge size={18} />,           path: "/super-admin/logs",            roles: ["super_admin"] },
  { key: "sa-support",         label: "Support",          icon: <LifeBuoy size={18} />,        path: "/super-admin/support",         roles: ["super_admin"] },
  { key: "sa-videos",          label: "Video Management", icon: <Video size={18} />,           path: "/super-admin/videos",          roles: ["super_admin"] },
  { key: "sa-manage-pages",    label: "Manage Pages",     icon: <FileText size={18} />,        path: "/super-admin/manage-pages",    roles: ["super_admin"] },
  { key: "sa-won-leads",       label: "Won Leads",        icon: <Award size={18} />,           path: "/super-admin/won-leads",       roles: ["super_admin"] },
  // Hero Section, Landing FAQ, Specialities, and SEO Settings are consolidated
  // under the single "Website Content" item in the sidebar profile popup
  // (tabbed shell at /super-admin/landing-page — see Sidebar.tsx). Theme
  // Settings alone remains in the profile popup alongside it.
  // Custom Fields menu hidden from the sidebar (page still reachable by URL).
  // { key: "sa-custom-fields",   label: "Custom Fields",    icon: <SlidersHorizontal size={18} />,   path: "/super-admin/custom-fields",   roles: ["super_admin"] },
];

// ─── App static menu (fallback / tenant_admin defaults) ──────────────
export const appMenu: MenuEntry[] = [
  { key: "app-dashboard",     label: "Dashboard",       icon: <LayoutDashboard size={18} />, path: "/app/dashboard",     roles: ["tenant_admin", "staff_user"] },
  { key: "app-leads",         label: "Leads",           icon: <Users size={18} />,           path: "/app/leads",         roles: ["tenant_admin", "staff_user"] },
  { key: "app-conversations", label: "Chats",   icon: <MessagesSquare size={18} />,  path: "/app/conversations", roles: ["tenant_admin", "staff_user"] },
  { key: "app-ai-chat",       label: "AI Chat",         icon: <Sparkles size={18} />,        path: "/app/ai-chat",       roles: ["tenant_admin"] },
  { key: "app-campaigns",     label: "Campaigns",       icon: <MessageSquare size={18} />,   path: "/app/campaigns",     roles: ["tenant_admin"] },
  { key: "app-faq",           label: "AI Knowledge Base", icon: <HelpCircle size={18} />, path: "/app/faq",           roles: ["tenant_admin"] },
  { key: "app-pricing",       label: "Pricing",         icon: <Receipt size={18} />,         path: "/app/pricing",       roles: ["tenant_admin"] },
  // { key: "app-automation",    label: "Automation",      icon: <Workflow size={18} />,        path: "/app/automation",    roles: ["tenant_admin"] },
  // Integrations retired — consolidated into App Connections (/app/connections).
  // The old /app/integrations route survives as a redirect for existing bookmarks.
  { key: "app-connections",   label: "App Connections", icon: <Plug size={18} />,            path: "/app/connections",   roles: ["tenant_admin"] },
  { key: "app-settings",      label: "Settings",        icon: <Settings size={18} />,        path: "/app/settings",      roles: ["tenant_admin"] },
  { key: "app-billing",       label: "Billing",         icon: <CreditCard size={18} />,      path: "/app/billing",       roles: ["tenant_admin"] },
  { key: "users",             label: "Users",           icon: <Users size={18} />,           path: "/app/users",         roles: ["tenant_admin"] },
  { key: "app-theme-settings", label: "Theme Settings", icon: <Palette size={18} />,        path: "/app/theme-settings", roles: ["tenant_admin"] },
  { key: "app-specialities",  label: "Specialities",    icon: <Stethoscope size={18} />,     path: "/app/specialities",  roles: ["tenant_admin"] },
  { key: "app-support",       label: "Support",         icon: <LifeBuoy size={18} />,        path: "/app/support",       roles: ["tenant_admin", "staff_user"] },
  { key: "app-guide",         label: "User's Guide",    icon: <PlayCircle size={18} />,      path: "/app/guide",         roles: ["tenant_admin", "staff_user"] },
  { key: "app-won-leads",     label: "Won Leads",       icon: <Award size={18} />,           path: "/app/won-leads",     roles: ["tenant_admin"] },
];

// ─── Icon map (backend stores icon name as string) ──────────────────
const s = 18;
const ICON_MAP: Record<string, JSX.Element> = {
  Activity: <Activity size={s} />,
  AlertCircle: <AlertCircle size={s} />,
  AlertTriangle: <AlertTriangle size={s} />,
  Ambulance: <Ambulance size={s} />,
  AppWindow: <AppWindow size={s} />,
  ArrowLeft: <ArrowLeft size={s} />,
  ArrowRight: <ArrowRight size={s} />,
  AtSign: <AtSign size={s} />,
  Award: <Award size={s} />,
  BadgeDollarSign: <BadgeDollarSign size={s} />,
  BadgePlus: <BadgePlus size={s} />,
  Banknote: <Banknote size={s} />,
  BarChart2: <BarChart2 size={s} />,
  BarChart3: <BarChart3 size={s} />,
  BarChart4: <BarChart4 size={s} />,
  Bell: <Bell size={s} />,
  BellRing: <BellRing size={s} />,
  Blocks: <Blocks size={s} />,
  BookOpen: <BookOpen size={s} />,
  Bookmark: <Bookmark size={s} />,
  Bot: <Bot size={s} />,
  Brain: <Brain size={s} />,
  BrainCircuit: <BrainCircuit size={s} />,
  Brush: <Brush size={s} />,
  Building: <Building size={s} />,
  Building2: <Building2 size={s} />,
  Cable: <Cable size={s} />,
  Calendar: <Calendar size={s} />,
  CalendarCheck: <CalendarCheck size={s} />,
  CalendarDays: <CalendarDays size={s} />,
  Camera: <Camera size={s} />,
  Check: <Check size={s} />,
  CheckCircle: <CheckCircle size={s} />,
  CircleDollarSign: <CircleDollarSign size={s} />,
  CircleUser: <CircleUser size={s} />,
  ClipboardCheck: <ClipboardCheck size={s} />,
  ClipboardList: <ClipboardList size={s} />,
  Clock: <Clock size={s} />,
  Cloud: <Cloud size={s} />,
  CloudUpload: <CloudUpload size={s} />,
  Cog: <Cog size={s} />,
  Compass: <Compass size={s} />,
  Contact: <Contact size={s} />,
  Copy: <Copy size={s} />,
  Cpu: <Cpu size={s} />,
  CreditCard: <CreditCard size={s} />,
  Cross: <Cross size={s} />,
  Database: <Database size={s} />,
  DollarSign: <DollarSign size={s} />,
  Download: <Download size={s} />,
  ExternalLink: <ExternalLink size={s} />,
  Eye: <Eye size={s} />,
  EyeOff: <EyeOff size={s} />,
  Factory: <Factory size={s} />,
  File: <File size={s} />,
  FileCheck: <FileCheck size={s} />,
  FilePlus: <FilePlus size={s} />,
  FileSearch: <FileSearch size={s} />,
  FileText: <FileText size={s} />,
  Filter: <Filter size={s} />,
  Fingerprint: <Fingerprint size={s} />,
  Flag: <Flag size={s} />,
  Folder: <Folder size={s} />,
  FolderOpen: <FolderOpen size={s} />,
  Gauge: <Gauge size={s} />,
  Gift: <Gift size={s} />,
  Globe: <Globe size={s} />,
  GraduationCap: <GraduationCap size={s} />,
  Grid: <Grid size={s} />,
  HardDrive: <HardDrive size={s} />,
  Hash: <Hash size={s} />,
  Headphones: <Headphones size={s} />,
  Heart: <Heart size={s} />,
  HeartPulse: <HeartPulse size={s} />,
  HelpCircle: <HelpCircle size={s} />,
  Home: <Home size={s} />,
  Hospital: <Hospital size={s} />,
  Hotel: <Hotel size={s} />,
  Hourglass: <Hourglass size={s} />,
  Image: <ImageIcon size={s} aria-label="Image" />,
  Inbox: <Inbox size={s} />,
  IndianRupee: <IndianRupee size={s} />,
  Info: <Info size={s} />,
  Key: <Key size={s} />,
  KeyRound: <KeyRound size={s} />,
  Landmark: <Landmark size={s} />,
  Layers: <Layers size={s} />,
  LayoutDashboard: <LayoutDashboard size={s} />,
  LayoutGrid: <LayoutGrid size={s} />,
  LayoutList: <LayoutList size={s} />,
  LifeBuoy: <LifeBuoy size={s} />,
  Lightbulb: <Lightbulb size={s} />,
  LineChart: <LineChart size={s} />,
  Link: <Link size={s} />,
  List: <List size={s} />,
  Lock: <Lock size={s} />,
  Mail: <Mail size={s} />,
  MailOpen: <MailOpen size={s} />,
  Map: <Map size={s} />,
  MapPin: <MapPin size={s} />,
  Menu: <Menu size={s} />,
  MessageCircle: <MessageCircle size={s} />,
  MessageSquare: <MessageSquare size={s} />,
  MessagesSquare: <MessagesSquare size={s} />,
  Mic: <Mic size={s} />,
  Microscope: <Microscope size={s} />,
  Minus: <Minus size={s} />,
  Monitor: <Monitor size={s} />,
  Music: <Music size={s} />,
  Navigation: <Navigation size={s} />,
  Notebook: <Notebook size={s} />,
  Package: <Package size={s} />,
  Package2: <Package2 size={s} />,
  PackageCheck: <PackageCheck size={s} />,
  Palette: <Palette size={s} />,
  PanelLeft: <PanelLeft size={s} />,
  Phone: <Phone size={s} />,
  PhoneCall: <PhoneCall size={s} />,
  PieChart: <PieChart size={s} />,
  PiggyBank: <PiggyBank size={s} />,
  Pill: <Pill size={s} />,
  Play: <Play size={s} />,
  PlayCircle: <PlayCircle size={s} />,
  Plug: <Plug size={s} />,
  Plug2: <Plug2 size={s} />,
  PlugZap: <PlugZap size={s} />,
  PlugZap2: <PlugZap2 size={s} />,
  Plus: <Plus size={s} />,
  Printer: <Printer size={s} />,
  Puzzle: <Puzzle size={s} />,
  QrCode: <QrCode size={s} />,
  Receipt: <Receipt size={s} />,
  RefreshCw: <RefreshCw size={s} />,
  RotateCcw: <RotateCcw size={s} />,
  Scan: <Scan size={s} />,
  ScanFace: <ScanFace size={s} />,
  Search: <Search size={s} />,
  Send: <Send size={s} />,
  Server: <Server size={s} />,
  Settings: <Settings size={s} />,
  Share2: <Share2 size={s} />,
  Shield: <Shield size={s} />,
  ShieldCheck: <ShieldCheck size={s} />,
  ShoppingBag: <ShoppingBag size={s} />,
  ShoppingCart: <ShoppingCart size={s} />,
  SidebarOpen: <SidebarOpen size={s} />,
  SlidersHorizontal: <SlidersHorizontal size={s} />,
  Smartphone: <Smartphone size={s} />,
  Sparkles: <Sparkles size={s} />,
  Star: <Star size={s} />,
  Stethoscope: <Stethoscope size={s} />,
  Store: <Store size={s} />,
  Syringe: <Syringe size={s} />,
  Table: <Table size={s} />,
  Tablet: <Tablet size={s} />,
  Tag: <Tag size={s} />,
  Tags: <Tags size={s} />,
  Thermometer: <Thermometer size={s} />,
  Timer: <Timer size={s} />,
  Trash2: <Trash2 size={s} />,
  TrendingDown: <TrendingDown size={s} />,
  TrendingUp: <TrendingUp size={s} />,
  Unlock: <Unlock size={s} />,
  Upload: <Upload size={s} />,
  UserCheck: <UserCheck size={s} />,
  UserCircle: <UserCircle size={s} />,
  UserCog: <UserCog size={s} />,
  UserPlus: <UserPlus size={s} />,
  UserX: <UserX size={s} />,
  Users: <Users size={s} />,
  Video: <Video size={s} />,
  Wallet: <Wallet size={s} />,
  Wand2: <Wand2 size={s} />,
  Warehouse: <Warehouse size={s} />,
  Webhook: <Webhook size={s} />,
  Workflow: <Workflow size={s} />,
  Wrench: <Wrench size={s} />,
  X: <X size={s} />,
  XCircle: <XCircle size={s} />,
  Zap: <Zap size={s} />,
};

function getIcon(iconName: string | null | undefined): JSX.Element {
  if (iconName && ICON_MAP[iconName]) return ICON_MAP[iconName];
  return <LayoutDashboard size={18} />;
}

// Menus that must additionally be gated by the tenant's resolved plan feature flags,
// on top of the existing RBAC "view" permission check. Keyed by menu slug -> the
// PlanFeatureFlags key that must be truthy for the menu item to appear in the sidebar.
// Add one entry here for each future plan-gated menu item.
const MENU_FEATURE_REQUIREMENTS: Partial<Record<string, keyof PlanFeatureFlags>> = {
  "app-specialities": "specialities",
};

/**
 * Build a sidebar menu from backend menuPermissions.
 * Only menus where the user has at least "view" permission are shown, and menus
 * listed in MENU_FEATURE_REQUIREMENTS are additionally hidden when the tenant's
 * plan does not include the required feature flag.
 */
export function buildMenuFromPermissions(
  menuPermissions: MenuPermission[],
  role: Role,
  featureFlags?: PlanFeatureFlags
): MenuEntry[] {
  const getSidebarLabel = (slug: string, defaultLabel: string) => {
    if (slug === "app-conversations") return "Chats";
    return defaultLabel;
  };

  return menuPermissions
    .filter((mp) => {
      if (!mp.permissions.includes("view")) return false;

      const slug = (mp.menu.slug ?? "").toLowerCase().trim();
      const segment = slug.startsWith("app-") ? slug.slice(4) : slug;

      // Roles menu is visible only to super admins.
      if ((slug === "roles" || segment === "roles") && role !== "super_admin") {
        return false;
      }

      // Plans menu is visible only to super admins.
      if ((slug === "plans" || segment === "plans") && role !== "super_admin") {
        return false;
      }

      // Guide menu requires view_all permission to appear in sidebar
      if (slug === "app-guide" && !mp.permissions.includes("view_all")) {
        return false;
      }

      // Plan feature-gating: hide menus whose required feature flag isn't enabled
      // on the tenant's resolved plan, even if the role has "view" permission.
      const requiredFeature = MENU_FEATURE_REQUIREMENTS[slug];
      if (requiredFeature && !featureFlags?.[requiredFeature]) {
        return false;
      }

      return true;
    })
    .sort((a, b) => {
      const aIsGuide = a.menu.slug === "app-guide";
      const bIsGuide = b.menu.slug === "app-guide";
      if (aIsGuide) return 1;
      if (bIsGuide) return -1;
      return a.menu.sort_order - b.menu.sort_order;
    })
    .map((mp) => {
      const slug    = mp.menu.slug;
      const segment = slug.startsWith("app-") ? slug.slice(4) : slug;
      return {
        key:   slug,
        label: getSidebarLabel(slug, mp.menu.name),
        icon:  getIcon(mp.menu.icon),
        path:  `/app/${segment}`,
        roles: [role],
      };
    });
}

/** Filter static menu by role (legacy helper, still used by super-admin layout). */
export const getVisibleMenu = (entries: MenuEntry[], role: MenuEntry["roles"][number] | null) =>
  entries.filter((entry) => (role ? entry.roles.includes(role) : false));
