const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

/**
 * One row per (tenant, slot) Instagram Business Account connection.
 *
 * CORRECTED MODEL (2026-07-31, supersedes the shared-platform-app OAuth
 * design): there is NO shared/global Meta App. Each clinic (tenant) brings
 * their OWN Meta Developer App — created and owned entirely on their own
 * developers.facebook.com account — and manually pastes their App ID, App
 * Secret, a long-lived Access Token, and their Instagram Business Account ID
 * into our settings UI. This is direct credential entry, NOT an OAuth
 * redirect flow. A shared platform-wide Meta App cannot be used by arbitrary
 * third-party Instagram accounts without them being added as test users on
 * that specific app ("Insufficient Developer Role"), which is exactly the
 * failure that triggered this correction.
 *
 * Every credential (App ID, App Secret, Access Token, IG Business Account
 * ID, the generated callback/webhook URL, and the generated webhook verify
 * token) is stored per-tenant in this table — never in a shared .env file —
 * so this scales to many independently-configured clinic Meta Apps.
 *
 * `webhook_verify_token` is generated by OUR backend (random string) and
 * shown to the clinic to paste into THEIR OWN Meta App's webhook config.
 * `meta_app_secret` is used to verify THAT tenant's inbound webhook HMAC
 * signature (X-Hub-Signature-256), since each clinic's app secret differs.
 */
const InstagramSession = sequelize.define(
  "InstagramSession",
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    tenant_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: { model: "users", key: "id" },
    },
    // 1-based slot number within the tenant (1 = first account, 2 = second, …).
    slot: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1,
    },
    // Optional friendly label the clinic can give the account ("Main IG").
    label: {
      type: DataTypes.STRING(60),
      allowNull: true,
      defaultValue: null,
    },
    status: {
      type: DataTypes.ENUM("disconnected", "connected", "token_expired", "revoked"),
      defaultValue: "disconnected",
    },
    // The clinic's OWN Meta App ID (from their developers.facebook.com app).
    meta_app_id: {
      type: DataTypes.STRING(64),
      allowNull: true,
      defaultValue: null,
    },
    // The clinic's OWN Meta App Secret. Used to verify THIS tenant's inbound
    // webhook HMAC signature (X-Hub-Signature-256) — each clinic's app secret
    // is different, so signature verification must look this up per-tenant.
    meta_app_secret: {
      type: DataTypes.STRING(255),
      allowNull: true,
      defaultValue: null,
    },
    // Generated by our backend, shown to the clinic to paste into THEIR
    // Meta App's webhook subscription config. Unique per (tenant, slot) row
    // so the GET verification handshake can look up the right tenant by
    // matching this value against the incoming hub.verify_token, in addition
    // to the URL path already identifying the tenant.
    webhook_verify_token: {
      type: DataTypes.STRING(64),
      allowNull: true,
      defaultValue: null,
    },
    // The connected Instagram Business Account's handle. Resolved via a
    // Graph API lookup-by-ID for display purposes only — best effort.
    ig_username: {
      type: DataTypes.STRING(60),
      allowNull: true,
      defaultValue: null,
    },
    // The Instagram Business Account ID — user-provided directly (no more
    // OAuth pages-list resolution). Primary identifier used in all
    // subsequent Graph API calls (/{ig-business-account-id}/messages, etc.).
    ig_business_account_id: {
      type: DataTypes.STRING(64),
      allowNull: true,
      defaultValue: null,
    },
    // The linked Facebook Page ID. Optional — not required for direct
    // credential entry (the clinic supplies the IG Business Account ID
    // directly), but kept for display/reference if the clinic provides it.
    facebook_page_id: {
      type: DataTypes.STRING(64),
      allowNull: true,
      defaultValue: null,
    },
    // The long-lived Access Token, generated by the CLINIC on their own Meta
    // dashboard (Graph API Explorer or their own server-side token exchange)
    // and pasted in directly — never obtained via an OAuth flow through our
    // backend. Stored as plaintext, matching this codebase's existing
    // precedent of no field-level encryption-at-rest for sensitive strings —
    // flagged for pr-reviewer as a security consideration, not silently decided.
    access_token: {
      type: DataTypes.TEXT,
      allowNull: true,
      defaultValue: null,
    },
    // Optional expiry timestamp IF the clinic knows/provides one. Meta tokens
    // obtained outside our own OAuth flow often don't self-report this
    // cleanly, so this is best-effort — `last_error` is the primary signal
    // for "this token stopped working," not a refresh timer.
    token_expires_at: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: null,
    },
    // Last Graph API error surfaced to the UI (e.g. "Token expired or
    // invalid — please generate a fresh token and re-paste it.").
    last_error: {
      type: DataTypes.STRING(255),
      allowNull: true,
      defaultValue: null,
    },
  },
  {
    tableName: "instagram_sessions",
    timestamps: true,
    underscored: true,
    indexes: [
      // A tenant can have at most one row per slot.
      { unique: true, fields: ["tenant_id", "slot"] },
    ],
  }
);

module.exports = InstagramSession;
